---
version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-twodii}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_HOST: "${POSTGRES_HOST:-db}"
